# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blacklight_range_limit}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Rochkind"]
  s.date = %q{2010-07-22}
  s.description = %q{Add integer range limit/profile to a Blacklight app}
  s.email = %q{jonathan@dnil.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/helpers/range_limit_helper.rb",
     "app/views/blacklight_range_limit/_range_limit_panel.html.erb",
     "app/views/blacklight_range_limit/_range_segments.html.erb",
     "assets/javascripts/range_limit_distro_facets.js",
     "assets/javascripts/range_limit_slider.js",
     "assets/stylesheets/blacklight_range_limit.css",
     "blacklight_range_limit.gemspec",
     "config/routes.rb",
     "install.rb",
     "lib/blacklight_range_limit.rb",
     "lib/blacklight_range_limit/controller_override.rb",
     "lib/blacklight_range_limit/segment_calculation.rb",
     "lib/blacklight_range_limit/view_helper_override.rb",
     "rails/init.rb",
     "tasks/blacklight_range_limit_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/projectblacklight/blacklight_range_limit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Add integer range limit/profile to a Blacklight app}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

